services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: subscriptions
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
  server:
    build:
      context: .
      target: final
  ports:
    - "8080:8080" # Puerto HTTP
    - "8443:443"  # Puerto HTTPS (mapea el puerto 443 del contenedor al 8443 en tu máquina)
  environment:
    - ASPNETCORE_URLS=https://+:443;http://+:8080 # Define los puertos HTTP y HTTPS
    - ASPNETCORE_Kestrel__Certificates__Default__Password=Dimas2020
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/your_cert.pfx
  volumes:
    - ./certs:/https:ro # Monta el certificado SSL
